# Generated by Django 5.2 on 2025-04-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Class', '0003_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
                ('class_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.classes')),
            ],
        ),
    ]
