# Generated by Django 5.2 on 2025-04-12 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_notes_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.student'),
            preserve_default=False,
        ),
    ]
