# Generated by Django 5.1.7 on 2025-03-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founded_by', models.CharField(max_length=100)),
                ('founded_in', models.DateField()),
                ('name', models.CharField(max_length=2)),
                ('type', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School')], max_length=20)),
            ],
        ),
    ]
