# Generated by Django 5.2 on 2025-04-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
